name: Ajit Selenium Java Cucumber Tests

on:
  workflow_dispatch:   # 👈 Manual run (GitHub Actions से "Run workflow" button)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Run Tests and Generate Cucumber Reports
      - name: Run Tests with Maven
        run: mvn clean verify -DskipTests=false

      # 5. Upload Cucumber HTML Reports as Artifact
      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: target/cucumber-reports
