name: Manual CI/CD - Maven Cucumber

# Trigger manually via GitHub Actions UI
on:
  workflow_dispatch:

jobs:
  manual-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build project and run tests
      - name: Run Maven Tests
        run: mvn clean verify

      # Step 5: Generate Cucumber HTML report
      - name: Generate Cucumber Report
        run: mvn net.masterthought:maven-cucumber-reporting:5.7.5:generate

      # Step 6: Upload HTML report artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: target/cucumber-report
