name: Java CI with Maven and Cucumber

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build and run tests
      - name: Run Maven tests
        run: mvn clean verify

      # Upload JSON report (so cucumber-reporting can use it)
      - name: Upload Cucumber JSON
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-json
          path: target/cucumber.json

      # Generate Cucumber HTML report
      - name: Generate Cucumber Report
        run: mvn net.masterthought:maven-cucumber-reporting:5.7.5:generate

      # Upload HTML report as artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: target/cucumber-report
