name: Selenium Java Cucumber Tests

on:
  workflow_dispatch:   # Manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Run Tests
      - name: Run Tests
        run: mvn clean test

      # Debug: check json file exists
      - name: Check cucumber.json
        run: ls -l target/cucumber.json || echo "cucumber.json not found!"

      # Generate Report
      - name: Generate Cucumber Report
        run: mvn verify

      # Upload HTML report as artifact
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-report
